# Generated by Django 4.2.6 on 2023-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='ano_publicacao',
            field=models.IntegerField(null=True, verbose_name='ano_publicacao'),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='autor',
            field=models.CharField(max_length=200, null=True, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(max_length=200, null=True, verbose_name='isbn'),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='numero_paginas',
            field=models.IntegerField(null=True, verbose_name='numero_paginas'),
        ),
    ]
